#ifndef WATCHDOGTIMER_GLOBAL_H
#define WATCHDOGTIMER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WATCHDOGTIMER_LIBRARY)
#  define WATCHDOGTIMER_EXPORT Q_DECL_EXPORT
#else
#  define WATCHDOGTIMER_EXPORT Q_DECL_IMPORT
#endif

#endif // WATCHDOGTIMER_GLOBAL_H
